server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
#          uri: file:///C://Dev//Projects//Study//inflearn//git-local-repo
          uri: https://github.com/Hyuck9/spring-cloud-config
#          username: [my username]
#          password: [my password]
